# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-02-20 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(default='', upload_to='images/')),
                ('token_count', models.IntegerField(default=0)),
                ('access_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
