# Generated by Django 4.0.3 on 2022-03-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subcategories', to='baba_barter.category')),
            ],
        ),
        migrations.CreateModel(
            name='Swappable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=10)),
                ('short_description', models.TextField(max_length=50)),
                ('long_description', models.TextField()),
                ('notes', models.TextField()),
                ('value', models.IntegerField(default=0)),
                ('currency', models.CharField(default='', max_length=50)),
                ('score', models.IntegerField(default=100)),
                ('condition', models.IntegerField(default=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_swappables', to='baba_barter.category')),
                ('sub_categories', models.ManyToManyField(default='', related_name='all_swappables', to='baba_barter.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('description', models.TextField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=10)),
                ('token_count', models.IntegerField(default=0)),
                ('access_level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=100)),
                ('has_paid', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_user_flag', to='baba_barter.user')),
                ('flagger_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagger_user_flag', to='baba_barter.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='baba_barter.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='report_user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flag_image', to='baba_barter.userflag')),
            ],
        ),
        migrations.CreateModel(
            name='SwappableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='swappable_images/')),
                ('main', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swappable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swappable_image', to='baba_barter.swappable')),
            ],
        ),
        migrations.CreateModel(
            name='SwappableAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swappable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swappable_address', to='baba_barter.swappable')),
            ],
        ),
        migrations.AddField(
            model_name='swappable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_swappables', to='baba_barter.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(default='', related_name='users', to='baba_barter.user'),
        ),
    ]
