# Generated by Django 4.0.3 on 2022-03-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwappableFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_swappable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_swappable_flag', to='baba_barter.swappable')),
                ('flagger_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swappable_flagger_user_flag', to='baba_barter.user')),
            ],
        ),
        migrations.CreateModel(
            name='SwappableFlagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='report_swappable_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swappable_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swappable_flag_image', to='baba_barter.swappableflag')),
            ],
        ),
    ]
