# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-02-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0003_auto_20220225_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='swappable',
            name='currrency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='swappable',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='swappable',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
