# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-02-27 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0004_auto_20220226_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swappable',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='swappable',
            name='sub_categories',
            field=models.ManyToManyField(default='', related_name='all_swappables', to='baba_barter.SubCategory'),
        ),
        migrations.AlterField(
            model_name='swappable',
            name='currrency',
            field=models.CharField(default='', max_length=50),
        ),
    ]
