# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-02-27 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0005_auto_20220227_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swappable',
            old_name='currrency',
            new_name='currency',
        ),
    ]
