# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0006_auto_20220227_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(default='', related_name='user_categories', to='baba_barter.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
