# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0007_auto_20220301_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images/'),
        ),
    ]
