# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0010_auto_20220304_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='swappableimage',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userimage',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
