# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0011_auto_20220305_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwappableAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('postalcode', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swappable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swappable_address', to='baba_barter.Swappable')),
            ],
        ),
    ]
