# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baba_barter', '0013_auto_20220316_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='report_user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flag_image', to='baba_barter.UserFlag')),
            ],
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='selected',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userflag',
            name='flagged_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_user_flag', to='baba_barter.User'),
        ),
        migrations.AddField(
            model_name='userflag',
            name='flagger_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagger_user_flag', to='baba_barter.User'),
        ),
    ]
